USE [master]
GO

/****** Object:  Database [UsersAmadeusAirline]    Script Date: 26/09/2024 5:05:17 p. m. ******/
CREATE DATABASE [UsersAmadeusAirline]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'UsersAmadeusAirline', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\UsersAmadeusAirline.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'UsersAmadeusAirline_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\UsersAmadeusAirline_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [UsersAmadeusAirline].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [UsersAmadeusAirline] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [UsersAmadeusAirline] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [UsersAmadeusAirline] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [UsersAmadeusAirline] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [UsersAmadeusAirline] SET ARITHABORT OFF 
GO

ALTER DATABASE [UsersAmadeusAirline] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [UsersAmadeusAirline] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [UsersAmadeusAirline] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [UsersAmadeusAirline] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [UsersAmadeusAirline] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [UsersAmadeusAirline] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [UsersAmadeusAirline] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [UsersAmadeusAirline] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [UsersAmadeusAirline] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [UsersAmadeusAirline] SET  DISABLE_BROKER 
GO

ALTER DATABASE [UsersAmadeusAirline] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [UsersAmadeusAirline] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [UsersAmadeusAirline] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [UsersAmadeusAirline] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [UsersAmadeusAirline] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [UsersAmadeusAirline] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [UsersAmadeusAirline] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [UsersAmadeusAirline] SET RECOVERY FULL 
GO

ALTER DATABASE [UsersAmadeusAirline] SET  MULTI_USER 
GO

ALTER DATABASE [UsersAmadeusAirline] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [UsersAmadeusAirline] SET DB_CHAINING OFF 
GO

ALTER DATABASE [UsersAmadeusAirline] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [UsersAmadeusAirline] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [UsersAmadeusAirline] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [UsersAmadeusAirline] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [UsersAmadeusAirline] SET QUERY_STORE = OFF
GO

ALTER DATABASE [UsersAmadeusAirline] SET  READ_WRITE 
GO


